In [2]:
import pandas as pd
import numpy as np
import math as math
import os
import matplotlib.pyplot as plt
import datetime

In [4]:
pd.options.display.float_format = "{:,.2f}".format

In [144]:
faktury_z_kontrahentami = pd.read_excel('C:\\DANE_2024\\AUDYT\\CARMEN 2024\\UZGODNIENIA\\faktury+kontrahenci.xlsx', index_col='Numer faktury')

In [146]:
faktury_z_kontrahentami.head()

                 Unnamed: 0                                        kontrahenci
Numer faktury
9011388596                0                                           IMPER_TO
3088301082                1                                           BAT_TRAD
3088301079                2                                           BAT_TRAD
FA/1/01/2024/DA           3                                  DPSUJ___,DPSUJ___
FA/1/01/2024/JS           4  YHORTUS_,ŁZAJA_AN,DUMA_BYST_PLA,HWANDA,PASCAL,...

In [164]:
faktury_z_kontrahentami.kontrahenci.str.split(',',expand=True)[0].value_counts()

0
JOHNY_TABAK_PLA    1592
PSS_BIE            1326
AN_MAR_PLA         1021
VMULTI__            825
EMI_PLATN           773
                   ...
_MARIUSZ_KOZIOŁ       1
KAJA_ŻAK              1
WIZAX                 1
VWROBEL               1
9010799               1
Name: count, Length: 774, dtype: int64

In [152]:
faktury_z_kontrahentami

,Unnamed: 0,kontrahenci
Numer faktury,,
9011388596,0,IMPER_TO
3088301082,1,BAT_TRAD
3088301079,2,BAT_TRAD
FA/1/01/2024/DA,3,"DPSUJ___,DPSUJ___"
FA/1/01/2024/JS,4,"YHORTUS_,ŁZAJA_AN,DUMA_BYST_PLA,HWANDA,PASCAL,..."
...,...,...
Detal 1 z 2024-12-31,16686,"!NIEOKREŚLONY!,!NIEOKREŚLONY!,!NIEOKREŚLONY!,!..."
4455/2024/06,16687,PHILIP_D
ewid.pomyłek Par 20241223210546146,16688,NaN
ewid.pomyłek Par 20241221114617724,16689,NaN
ewid.pomyłek Par 20241203075642154,16690,NaN